### PR TITLE
Additional checking to register component only once

### PR DESCRIPTION
**Pull request by vvscode**
After Ember update there are code, which check if component was already registered. And on trying to reregister component -- it's throw an error. 

Old implementation register component on every initialization ( we've got an error on multiple wysiwyg at form )

### CODE REVIEW

**Comment by asaf** [comment]
Hey @vvscode,

Would you like to be a maintainer of the project?

Thanks

**Comment by vvscode** [comment]
@asaf I'm not sure )) We use component in our project, and in general it works fine for me ( cause we can update structure for modern ember ). I'm ready to contribute if you have some issues --just create issue and add mention for me

**Comment by asaf** [comment]
@vvscode I can make you a moderator and you can actually merge these changes by yourself :-)

**Comment by vvscode** [comment]
@asaf  thx. Hope I'll justify your trust

**Pull request merged**
